version: 2.1
executors:
  java:
    docker:
      - image: openjdk:7-jdk-alpine
jobs:
  build:
    executor: java
    steps:
      - checkout
      - run: ./gradlew :clean
      - run: ./gradlew :build
workflows:
  build:
    jobs:
      - build
