version: 2.1
executors:
  java:
    docker:
      - image: openjdk:8-jdk
jobs:
  build:
    executor: java
    steps:
      - checkout
      - run: java -version
      - run: ./gradlew clean
      - run: ./gradlew test
      - run: ./gradlew shadowJar
